import { RoleName } from '../../generated/prisma';
import { PERMISSIONS, PermissionName } from './permission.constant';

export const ROLE_PERMISSIONS: Record<RoleName, readonly PermissionName[]> = {
  [RoleName.SUPER_ADMIN]: [],

  [RoleName.OWNER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_OCCUPANCY,
    PERMISSIONS.DASHBOARD_VIEW_REVENUE,
    PERMISSIONS.DASHBOARD_VIEW_ARRIVALS,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTURES,
    PERMISSIONS.DASHBOARD_VIEW_IN_HOUSE,

    PERMISSIONS.RESERVATIONS_VIEW,

    PERMISSIONS.GUESTS_VIEW,

    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVENUE_VIEW,
    PERMISSIONS.REPORTS_OCCUPANCY_VIEW,
    PERMISSIONS.REPORTS_CANCELLATION_VIEW,
  ],

  [RoleName.GENERAL_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_OCCUPANCY,
    PERMISSIONS.DASHBOARD_VIEW_REVENUE,
    PERMISSIONS.DASHBOARD_VIEW_ARRIVALS,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTURES,
    PERMISSIONS.DASHBOARD_VIEW_IN_HOUSE,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_CANCEL,
    PERMISSIONS.RESERVATIONS_CHECK_IN,
    PERMISSIONS.RESERVATIONS_CHECK_OUT,
    PERMISSIONS.RESERVATIONS_NO_SHOW,
    PERMISSIONS.RESERVATIONS_CHANGE_ROOM,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.ROOMS_ASSIGN,
    PERMISSIONS.ROOMS_BLOCK,

    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_COLLECT,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVENUE_VIEW,
    PERMISSIONS.REPORTS_OCCUPANCY_VIEW,
    PERMISSIONS.REPORTS_CANCELLATION_VIEW,
  ],

  [RoleName.HOTEL_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_CANCEL,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,

    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_CREATE,
    PERMISSIONS.ROLES_UPDATE,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
  ],

  [RoleName.FRONT_DESK_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_ARRIVALS,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTURES,
    PERMISSIONS.DASHBOARD_VIEW_IN_HOUSE,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_CANCEL,
    PERMISSIONS.RESERVATIONS_CHECK_IN,
    PERMISSIONS.RESERVATIONS_CHECK_OUT,
    PERMISSIONS.RESERVATIONS_NO_SHOW,
    PERMISSIONS.RESERVATIONS_CHANGE_ROOM,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.ROOMS_ASSIGN,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_COLLECT,
  ],

  [RoleName.FRONT_DESK_AGENT]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_ARRIVALS,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTURES,
    PERMISSIONS.DASHBOARD_VIEW_IN_HOUSE,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_CHECK_IN,
    PERMISSIONS.RESERVATIONS_CHECK_OUT,
    PERMISSIONS.RESERVATIONS_NO_SHOW,
    PERMISSIONS.RESERVATIONS_CHANGE_ROOM,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.ROOMS_ASSIGN,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_COLLECT,
  ],

  [RoleName.RESERVATION_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_OCCUPANCY,
    PERMISSIONS.DASHBOARD_VIEW_ARRIVALS,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTURES,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.RESERVATIONS_CANCEL,
    PERMISSIONS.RESERVATIONS_NO_SHOW,
    PERMISSIONS.RESERVATIONS_CHANGE_ROOM,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_OCCUPANCY_VIEW,
    PERMISSIONS.REPORTS_CANCELLATION_VIEW,
  ],

  [RoleName.RESERVATION_AGENT]: [
    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.ROOMS_VIEW,
  ],

  [RoleName.HOUSEKEEPING_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_CREATE_TASK,
    PERMISSIONS.HOUSEKEEPING_ASSIGN_TASK,
    PERMISSIONS.HOUSEKEEPING_REASSIGN_TASK,
    PERMISSIONS.HOUSEKEEPING_INSPECT_ROOM,
    PERMISSIONS.GUESTS_VIEW,
  ],

  [RoleName.HOUSEKEEPER]: [
    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_START_TASK,
    PERMISSIONS.HOUSEKEEPING_COMPLETE_TASK,
    PERMISSIONS.HOUSEKEEPING_REPORT_ISSUE,
  ],

  [RoleName.MAINTENANCE_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_ASSIGN,
    PERMISSIONS.MAINTENANCE_REASSIGN,
    PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.MAINTENANCE_COMPLETE,
  ],

  [RoleName.MAINTENANCE_TECHNICIAN]: [
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_UPDATE,
    PERMISSIONS.MAINTENANCE_COMPLETE,
  ],

  [RoleName.ACCOUNTING_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_REVENUE,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_COLLECT,
    PERMISSIONS.PAYMENTS_REFUND,
    PERMISSIONS.PAYMENTS_VOID,

    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.INVOICES_UPDATE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVENUE_VIEW,
  ],

  [RoleName.ACCOUNTANT]: [
    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_COLLECT,

    PERMISSIONS.INVOICES_VIEW,
    PERMISSIONS.INVOICES_CREATE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVENUE_VIEW,
  ],

  [RoleName.RESTAURANT_MANAGER]: [
    PERMISSIONS.RESTAURANT_VIEW,
    PERMISSIONS.RESTAURANT_CREATE_ORDER,
    PERMISSIONS.RESTAURANT_UPDATE_ORDER,
    PERMISSIONS.RESTAURANT_CANCEL_ORDER,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_COLLECT,
  ],

  [RoleName.RESTAURANT_STAFF]: [
    PERMISSIONS.RESTAURANT_VIEW,
    PERMISSIONS.RESTAURANT_CREATE_ORDER,
    PERMISSIONS.RESTAURANT_UPDATE_ORDER,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.FOLIOS_ADD_CHARGE,
  ],

  [RoleName.INVENTORY_MANAGER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_DELETE,
    PERMISSIONS.INVENTORY_ADJUST,
  ],

  [RoleName.INVENTORY_STAFF]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
  ],

  [RoleName.SALES_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_OCCUPANCY_VIEW,
    PERMISSIONS.REPORTS_REVENUE_VIEW,
  ],

  [RoleName.SALES_AGENT]: [
    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.RESERVATIONS_CREATE,
    PERMISSIONS.RESERVATIONS_UPDATE,

    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.GUESTS_CREATE,
    PERMISSIONS.GUESTS_UPDATE,
  ],

  [RoleName.AUDITOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DASHBOARD_VIEW_OCCUPANCY,
    PERMISSIONS.DASHBOARD_VIEW_REVENUE,

    PERMISSIONS.RESERVATIONS_VIEW,
    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.ROOMS_VIEW,

    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,

    PERMISSIONS.FOLIOS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,

    PERMISSIONS.INVOICES_VIEW,

    PERMISSIONS.INVENTORY_VIEW,

    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVENUE_VIEW,
    PERMISSIONS.REPORTS_OCCUPANCY_VIEW,
    PERMISSIONS.REPORTS_CANCELLATION_VIEW,
  ],
};
